export const SEQUELIZE = 'SEQUELIZE';
export const DOCKER = 'DOCKER';

export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';

export const EXERCICE_REPOSITORY = 'EXERCICE_REPOSITORY';
export const EXERCICE_SET_REPOSITORY = 'EXERCICE_SET_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const SESSION_REPOSITORY = 'SESSION_REPOSITORY';
export const EXERCICE_PROGRESS_REPOSITORY = 'EXERCICE_SET_REPOSITORY';
